root: true
env:
  browser: true
  es2021: true
  jest: true
  node: true
extends:
  - eslint:recommended
  - prettier
parser: '@babel/eslint-parser'
parserOptions:
  ecmaVersion: 12
  sourceType: module
ignorePatterns:
  - dist
  - node_modules
  - src/coverage
rules: {}
